version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow FastAPI to interact with Docker
    depends_on:
      - python-executor  # Ensure the Python container is up before FastAPI starts
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  python-executor:
    image: python:3.9-slim  # Use the Python 3.9 slim image for execution
    command: tail -f /dev/null  # Keeps the container running
    volumes:
      - /tmp/code-execution:/app  # Temporary directory to execute code in

