//SORRY GUYS THIS IS FULLY GENERATED BY AI EXCEPT FOR LOOPS AND CONDITIONS


export const languageConfigs = {
  python: {
    snippets: [
      {
        label: "main",
        insertText: "if __name__ == \"__main__\":\n\t$0",
        doc: "Main entry point guard"
      },
      {
        label: "def",
        insertText: "def ${1:function_name}(${2:params}):\n\t${3:pass}\n\treturn $0",
        doc: "Function definition"
      },
      {
        label: "class",
        insertText: "class ${1:ClassName}:\n\tdef __init__(self${2:, args}):\n\t\t$0",
        doc: "Class definition"
      },
      {
        label: "for",
        insertText: "for ${1:item} in ${2:iterable}:\n\t$0",
        doc: "For loop"
      },
      {
        label: "try",
        insertText: "try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:e}:\n\t$0",
        doc: "Try-except block"
      },
      {
        label: "while",
        insertText: "while ${1:condition}:\n\t$0",
        doc: "While loop"
      },
      {
        label: "if",
        insertText: "if ${1:condition}:\n\t$0",
        doc: "If statement"
      },
      {
        label: "elif",
        insertText: "elif ${1:condition}:\n\t$0",
        doc: "Elif statement"
      },
      {
        label: "with",
        insertText: "with open('${1:filename}', '${2:r}') as ${3:f}:\n\t$0",
        doc: "With statement for file handling"
      },
      {
        label: "lambda",
        insertText: "lambda ${1:x}: ${2:x}$0",
        doc: "Lambda function"
      },
      {
        label: "list_comp",
        insertText: "[${1:item} for ${2:item} in ${3:iterable}]$0",
        doc: "List comprehension"
      },
      {
        label: "dict_comp",
        insertText: "{${1:key}: ${2:value} for ${3:item} in ${4:iterable}}$0",
        doc: "Dictionary comprehension"
      },
      {
        label: "property",
        insertText: "@property\ndef ${1:name}(self):\n\treturn self._${1:name}$0",
        doc: "Property decorator"
      },
      {
        label: "print",
        insertText: "print(${1:value})$0",
        doc: "Print to console"
      },
      {
        label: "input",
        insertText: "input(\"${1:prompt}: \")$0",
        doc: "Get user input"
      },
      {
        label: "len",
        insertText: "len(${1:sequence})$0",
        doc: "Get length"
      },
      {
        label: "range",
        insertText: "range(${1:start}, ${2:stop}, ${3:step})$0",
        doc: "Range function"
      },
      {
        label: "enumerate",
        insertText: "enumerate(${1:iterable})$0",
        doc: "Enumerate with index"
      },
      {
        label: "zip",
        insertText: "zip(${1:iter1}, ${2:iter2})$0",
        doc: "Zip iterables"
      },
      {
        label: "open",
        insertText: "open('${1:filename}', '${2:r}')$0",
        doc: "Open file"
      },
      {
        label: "import",
        insertText: "import ${1:module}$0",
        doc: "Import statement"
      },
      {
        label: "from",
        insertText: "from ${1:module} import ${2:name}$0",
        doc: "From import statement"
      },
      {
        label: "async_def",
        insertText: "async def ${1:function_name}(${2:params}):\n\t${3:pass}\n\treturn $0",
        doc: "Async function definition"
      },
      {
        label: "await",
        insertText: "await ${1:coroutine}$0",
        doc: "Await expression"
      }
    ]
  },
  c: {
    snippets: [
      {
        label: "main",
        insertText: "#include <stdio.h>\n\nint main() {\n\t$0\n\treturn 0;\n}",
        doc: "C main function"
      },
      {
        label: "func",
        insertText: "${1:int} ${2:function_name}(${3:params}) {\n\t$0\n}",
        doc: "Function definition"
      },
      {
        label: "for",
        insertText: "for (${1:int i = 0}; ${2:i < n}; ${3:i++}) {\n\t$0\n}",
        doc: "For loop"
      },
      {
        label: "struct",
        insertText: "struct ${1:name} {\n\t${2:int field};\n};",
        doc: "Struct definition"
      },
      {
        label: "while",
        insertText: "while (${1:condition}) {\n\t$0\n}",
        doc: "While loop"
      },
      {
        label: "if",
        insertText: "if (${1:condition}) {\n\t$0\n}",
        doc: "If statement"
      },
      {
        label: "switch",
        insertText: "switch (${1:variable}) {\n\tcase ${2:value}:\n\t\t$0\n\t\tbreak;\n\tdefault:\n\t\tbreak;\n}",
        doc: "Switch statement"
      },
      {
        label: "typedef",
        insertText: "typedef ${1:type} ${2:alias};$0",
        doc: "Typedef declaration"
      },
      {
        label: "malloc",
        insertText: "${1:type}* ${2:ptr} = (${1:type}*)malloc(${3:size} * sizeof(${1:type}));$0",
        doc: "Memory allocation"
      },
      {
        label: "free",
        insertText: "free(${1:ptr});\n${1:ptr} = NULL;$0",
        doc: "Free allocated memory"
      },
      {
        label: "printf",
        insertText: "printf(\"${1:format}\\n\", ${2:args});$0",
        doc: "Print formatted output"
      },
      {
        label: "scanf",
        insertText: "scanf(\"${1:format}\", &${2:variable});$0",
        doc: "Read formatted input"
      },
      {
        label: "include",
        insertText: "#include <${1:header.h}>$0",
        doc: "Include header"
      },
      {
        label: "define",
        insertText: "#define ${1:NAME} ${2:value}$0",
        doc: "Macro definition"
      },
      {
        label: "do_while",
        insertText: "do {\n\t$0\n} while (${1:condition});",
        doc: "Do-while loop"
      }
    ]
  },
  cpp: {
    snippets: [
      {
        label: "main",
        insertText: "#include <iostream>\nusing namespace std;\n\nint main() {\n\t$0\n\treturn 0;\n}",
        doc: "C++ main function"
      },
      {
        label: "class",
        insertText: "class ${1:ClassName} {\nprivate:\n\t${2:int member};\npublic:\n\t${1}();\n\t$0\n};",
        doc: "Class definition"
      },
      {
        label: "vector",
        insertText: "vector<${1:int}> ${2:vec};$0",
        doc: "Vector declaration"
      },
      {
        label: "func",
        insertText: "${1:void} ${2:function_name}(${3:params}) {\n\t$0\n}",
        doc: "Function definition"
      },
      {
        label: "for",
        insertText: "for (${1:int i = 0}; ${2:i < n}; ${3:i++}) {\n\t$0\n}",
        doc: "For loop"
      },
      {
        label: "for_auto",
        insertText: "for (auto ${1:item} : ${2:container}) {\n\t$0\n}",
        doc: "Range-based for loop"
      },
      {
        label: "while",
        insertText: "while (${1:condition}) {\n\t$0\n}",
        doc: "While loop"
      },
      {
        label: "if",
        insertText: "if (${1:condition}) {\n\t$0\n}",
        doc: "If statement"
      },
      {
        label: "try",
        insertText: "try {\n\t${1:code}\n} catch (const ${2:exception}& ${3:e}) {\n\t$0\n}",
        doc: "Try-catch block"
      },
      {
        label: "template",
        insertText: "template <typename ${1:T}>\n${2:void} ${3:function_name}(${4:params}) {\n\t$0\n}",
        doc: "Template function"
      },
      {
        label: "namespace",
        insertText: "namespace ${1:name} {\n\t$0\n}",
        doc: "Namespace definition"
      },
      {
        label: "cout",
        insertText: "cout << ${1:output} << endl;$0",
        doc: "Console output"
      },
      {
        label: "cin",
        insertText: "cin >> ${1:variable};$0",
        doc: "Console input"
      },
      {
        label: "struct",
        insertText: "struct ${1:Name} {\n\t${2:int field};\n};$0",
        doc: "Struct definition"
      },
      {
        label: "enum",
        insertText: "enum class ${1:Name} {\n\t${2:VALUE1},\n\t${3:VALUE2}\n};$0",
        doc: "Scoped enumeration"
      },
      {
        label: "constructor",
        insertText: "${1:ClassName}(${2:params}) : ${3:member}(${4:value}) {\n\t$0\n}",
        doc: "Constructor with initializer list"
      },
      {
        label: "std::cout",
        insertText: "std::cout << ${1:output} << std::endl;$0",
        doc: "Standard output"
      },
      {
        label: "std::cin",
        insertText: "std::cin >> ${1:variable};$0",
        doc: "Standard input"
      },
      {
        label: "std::string",
        insertText: "std::string ${1:str} = \"${2:value}\";$0",
        doc: "String declaration"
      },
      {
        label: "std::vector",
        insertText: "std::vector<${1:int}> ${2:vec};$0",
        doc: "Vector declaration"
      },
      {
        label: "std::map",
        insertText: "std::map<${1:KeyType}, ${2:ValueType}> ${3:map};$0",
        doc: "Map declaration"
      },
      {
        label: "std::pair",
        insertText: "std::pair<${1:Type1}, ${2:Type2}> ${3:pair};$0",
        doc: "Pair declaration"
      },
      {
        label: "push_back",
        insertText: "${1:container}.push_back(${2:value});$0",
        doc: "Add element to vector"
      },
      {
        label: "size",
        insertText: "${1:container}.size()$0",
        doc: "Get container size"
      },
      {
        label: "destructor",
        insertText: "~${1:ClassName}() {\n\t$0\n}",
        doc: "Destructor"
      }
    ]
  },
  go: {
    snippets: [
      {
        label: "main",
        insertText: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\t$0\n}",
        doc: "Go main function"
      },
      {
        label: "func",
        insertText: "func ${1:name}(${2:params}) ${3:returnType} {\n\t$0\n}",
        doc: "Function definition"
      },
      {
        label: "struct",
        insertText: "type ${1:Name} struct {\n\t${2:Field} ${3:Type}\n}$0",
        doc: "Struct definition"
      },
      {
        label: "interface",
        insertText: "type ${1:Name} interface {\n\t${2:Method}() ${3:returnType}\n}$0",
        doc: "Interface definition"
      },
      {
        label: "for",
        insertText: "for ${1:i} := ${2:0}; ${1:i} < ${3:n}; ${1:i}++ {\n\t$0\n}",
        doc: "For loop"
      },
      {
        label: "for_range",
        insertText: "for ${1:key}, ${2:value} := range ${3:slice} {\n\t$0\n}",
        doc: "For range loop"
      },
      {
        label: "if",
        insertText: "if ${1:condition} {\n\t$0\n}",
        doc: "If statement"
      },
      {
        label: "if_err",
        insertText: "if err != nil {\n\t$0\n}",
        doc: "Error handling"
      },
      {
        label: "switch",
        insertText: "switch ${1:variable} {\ncase ${2:value}:\n\t$0\ndefault:\n}",
        doc: "Switch statement"
      },
      {
        label: "var",
        insertText: "var ${1:name} ${2:type}$0",
        doc: "Variable declaration"
      },
      {
        label: "const",
        insertText: "const ${1:name} = ${2:value}$0",
        doc: "Constant declaration"
      },
      {
        label: "make_slice",
        insertText: "make([]${1:type}, ${2:len}, ${3:cap})$0",
        doc: "Make slice"
      },
      {
        label: "make_map",
        insertText: "make(map[${1:keyType}]${2:valueType})$0",
        doc: "Make map"
      },
      {
        label: "fmt.Println",
        insertText: "fmt.Println(${1:value})$0",
        doc: "Print line to console"
      },
      {
        label: "fmt.Printf",
        insertText: "fmt.Printf(\"${1:format}\\n\", ${2:args})$0",
        doc: "Print formatted output"
      },
      {
        label: "fmt.Sprintf",
        insertText: "fmt.Sprintf(\"${1:format}\", ${2:args})$0",
        doc: "Format string"
      },
      {
        label: "log.Fatal",
        insertText: "log.Fatal(${1:err})$0",
        doc: "Log fatal error and exit"
      },
      {
        label: "http.HandleFunc",
        insertText: "http.HandleFunc(\"${1:/path}\", ${2:handler})$0",
        doc: "HTTP handler function"
      },
      {
        label: "json.Marshal",
        insertText: "json.Marshal(${1:data})$0",
        doc: "JSON marshal"
      },
      {
        label: "json.Unmarshal",
        insertText: "json.Unmarshal(${1:data}, &${2:v})$0",
        doc: "JSON unmarshal"
      },
      {
        label: "go",
        insertText: "go ${1:function}()$0",
        doc: "Go routine"
      },
      {
        label: "chan",
        insertText: "chan ${1:type}$0",
        doc: "Channel type"
      },
      {
        label: "select",
        insertText: "select {\ncase ${1:msg} := <-${2:channel}:\n\t$0\ndefault:\n}",
        doc: "Select statement"
      },
      {
        label: "defer",
        insertText: "defer ${1:function}()$0",
        doc: "Defer statement"
      },
      {
        label: "method",
        insertText: "func (${1:receiver} ${2:Type}) ${3:methodName}(${4:params}) ${5:returnType} {\n\t$0\n}",
        doc: "Method definition"
      }
    ]
  },
  java: {
    snippets: [
      {
        label: "main",
        insertText: "public class Main {\n\tpublic static void main(String[] args) {\n\t\t$0\n\t}\n}",
        doc: "Java main method"
      },
      {
        label: "class",
        insertText: "public class ${1:ClassName} {\n\t${2:// fields}\n\t\n\tpublic ${1}() {\n\t\t$0\n\t}\n}",
        doc: "Class definition"
      },
      {
        label: "method",
        insertText: "public ${1:void} ${2:methodName}(${3:params}) {\n\t$0\n}",
        doc: "Method definition"
      },
      {
        label: "interface",
        insertText: "public interface ${1:InterfaceName} {\n\t${2:void} ${3:methodName}(${4:params});\n}$0",
        doc: "Interface definition"
      },
      {
        label: "abstract",
        insertText: "public abstract class ${1:ClassName} {\n\tpublic abstract ${2:void} ${3:methodName}(${4:params});\n}$0",
        doc: "Abstract class"
      },
      {
        label: "for",
        insertText: "for (${1:int i = 0}; ${2:i < n}; ${3:i++}) {\n\t$0\n}",
        doc: "For loop"
      },
      {
        label: "for_each",
        insertText: "for (${1:Type} ${2:item} : ${3:collection}) {\n\t$0\n}",
        doc: "Enhanced for loop"
      },
      {
        label: "while",
        insertText: "while (${1:condition}) {\n\t$0\n}",
        doc: "While loop"
      },
      {
        label: "if",
        insertText: "if (${1:condition}) {\n\t$0\n}",
        doc: "If statement"
      },
      {
        label: "try",
        insertText: "try {\n\t${1:code}\n} catch (${2:Exception} ${3:e}) {\n\t$0\n}",
        doc: "Try-catch block"
      },
      {
        label: "switch",
        insertText: "switch (${1:variable}) {\n\tcase ${2:value}:\n\t\t$0\n\t\tbreak;\n\tdefault:\n\t\tbreak;\n}",
        doc: "Switch statement"
      },
      {
        label: "enum",
        insertText: "public enum ${1:Name} {\n\t${2:VALUE1}, ${3:VALUE2}\n}$0",
        doc: "Enum definition"
      },
      {
        label: "constructor",
        insertText: "public ${1:ClassName}(${2:params}) {\n\t$0\n}",
        doc: "Constructor"
      },
      {
        label: "getter",
        insertText: "public ${1:Type} get${2:Property}() {\n\treturn ${3:field};\n}$0",
        doc: "Getter method"
      },
      {
        label: "setter",
        insertText: "public void set${1:Property}(${2:Type} ${3:value}) {\n\tthis.${4:field} = ${3:value};\n}$0",
        doc: "Setter method"
      },
      {
        label: "override",
        insertText: "@Override\npublic ${1:void} ${2:methodName}(${3:params}) {\n\t$0\n}",
        doc: "Override method"
      },
      {
        label: "static",
        insertText: "public static ${1:void} ${2:methodName}(${3:params}) {\n\t$0\n}",
        doc: "Static method"
      },
      {
        label: "toString",
        insertText: "@Override\npublic String toString() {\n\treturn \"${1:ClassName}{\" +\n\t\t\"${2:field}=\" + ${2:field} +\n\t\t'}';\n}$0",
        doc: "toString method"
      },
      {
        label: "System.out.println",
        insertText: "System.out.println(${1:value});$0",
        doc: "Print line to console"
      },
      {
        label: "System.out.print",
        insertText: "System.out.print(${1:value});$0",
        doc: "Print to console"
      },
      {
        label: "Scanner",
        insertText: "Scanner ${1:scanner} = new Scanner(System.in);$0",
        doc: "Scanner for input"
      },
      {
        label: "ArrayList",
        insertText: "ArrayList<${1:Type}> ${2:list} = new ArrayList<>();$0",
        doc: "ArrayList declaration"
      },
      {
        label: "HashMap",
        insertText: "HashMap<${1:KeyType}, ${2:ValueType}> ${3:map} = new HashMap<>();$0",
        doc: "HashMap declaration"
      },
      {
        label: "String.valueOf",
        insertText: "String.valueOf(${1:value})$0",
        doc: "Convert to string"
      },
      {
        label: "Integer.parseInt",
        insertText: "Integer.parseInt(${1:str})$0",
        doc: "Parse integer"
      },
      {
        label: "equals",
        insertText: "@Override\npublic boolean equals(Object obj) {\n\tif (this == obj) return true;\n\tif (obj == null || getClass() != obj.getClass()) return false;\n\t${1:ClassName} ${2:that} = (${1:ClassName}) obj;\n\treturn Objects.equals(${3:field}, ${2:that}.${3:field});\n}$0",
        doc: "equals method"
      }
    ]
  }
};